apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: cmss
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "password"         # replace in production
  MYSQL_DATABASE: "complaint_management_system"
  MYSQL_USER: "root"
